{% set name = "pytermgui" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytermgui-{{ version }}.tar.gz
  sha256: 3caceba8a02ef3c935f55913d1215e7fc9fbf1a2095f80b274b2142e99d57428

build:
  number: 0
  noarch: python
  entry_points:
    - ptg = pytermgui.cmd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - pytermgui
    - pytermgui.widgets
    - pytermgui.widgets.interactive
  commands:
    - pip check
    - ptg --help
  requires:
    - pip

about:
  home: https://github.com/bczsalba/pytermgui
  doc_url: ptg.bczsalba.com/pytermgui.html
  summary: A simple and robust terminal UI library, written in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
