{% set name = "pytermgui" %}
{% set version = "7.7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytermgui-{{ version }}.tar.gz
  sha256: f29598693ee299192f50be648933d65820e4b9a6e258007fd4bf898e3eb6c47d

build:
  number: 0
  noarch: python
  entry_points:
    - ptg = pytermgui.cmd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.26.1
    - hatch-fancy-pypi-readme
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - typing_extensions
    - wcwidth

test:
  source_files:
    - tests
  imports:
    - pytermgui
    - pytermgui.widgets
    - pytermgui.window_manager
  commands:
    - pip check
    - ptg --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - pyyaml
    - testfixtures
    - python {{ python_min }}

about:
  home: https://github.com/bczsalba/pytermgui
  doc_url: ptg.bczsalba.com/pytermgui.html
  summary: A simple and robust terminal UI library, written in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
