{% set name = "pytermgui" %}
{% set version = "7.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytermgui-{{ version }}.tar.gz
  sha256: 3a6211e872fae6b6a6445efff2260266f33d288a7ec64411238a673a23f333af

build:
  number: 0
  noarch: python
  entry_points:
    - ptg = pytermgui.cmd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling <=1.10.0
    - hatch-fancy-pypi-readme
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing_extensions

test:
  imports:
    - pytermgui
    - pytermgui.widgets
    - pytermgui.window_manager
  commands:
    - pip check
    - ptg --help
  requires:
    - pip

about:
  home: https://ptg.bczsalba.com/
  dev_url: https://github.com/bczsalba/pytermgui
  summary: A simple and robust terminal UI library, written in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
