{% set name = "pytermgui" %}
{% set version = "7.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytermgui-{{ version }}.tar.gz
  sha256: 030458be5c3cbeaab17fb9aa3d19e6232be4ce4a3f54418fe13bb97fdef446db

build:
  number: 0
  noarch: python
  entry_points:
    - ptg = pytermgui.cmd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - typing_extensions
    - wcwidth

test:
  source_files:
    - tests
  imports:
    - pytermgui
    - pytermgui.widgets
    - pytermgui.window_manager
  commands:
    - pip check
    - ptg --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - pyyaml
    - testfixtures

about:
  home: https://github.com/bczsalba/pytermgui
  doc_url: ptg.bczsalba.com/pytermgui.html
  summary: A simple and robust terminal UI library, written in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
