{% set name = "pytermgui" %}
{% set version = "7.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pytermgui-{{ version }}.tar.gz
  sha256: c4cea2e9a0e7b7900f47989278e9f3b88eddd6e6319df198d91484b6311d2368

build:
  number: 0
  noarch: python
  entry_points:
    - ptg = pytermgui.cmd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.26.1
    - hatch-fancy-pypi-readme
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - typing_extensions
    - wcwidth >=0.5

test:
  imports:
    - pytermgui
    - pytermgui.widgets
    - pytermgui.window_manager
  commands:
    - pip check
    - ptg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bczsalba/pytermgui
  doc_url: ptg.bczsalba.com/pytermgui.html
  summary: A simple and robust terminal UI library, written in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
